### ISSUE TITLE
No such file or directory: 'trained_models_structure.json'

### ISSUE THREAD

**Issue by RookieCXL** [lvapeab/nmt-keras#102]
After I trained.  
When I decode with this model， there was no file 'trained_models_structure.json'

-----------------------------
C:\Users\think\Desktop\nmt-keras-master>python sample_ensemble.py --models trained_models  --dataset datasets --text examples
[11/04/2019 08:36:05] Reading parameters from config.py
[11/04/2019 08:36:05] <<< Cupy not available. Using numpy. >>>
Using TensorFlow backend.
[11/04/2019 08:36:15] <<< Cupy not available. Using numpy. >>>
[11/04/2019 08:36:15] Using an ensemble of 1 models
[11/04/2019 08:36:15] <<< Loading model from trained_models_Model_Wrapper.pkl ... >>>
[11/04/2019 08:36:15] <<< Loading model from trained_models.h5 ... >>>
[11/04/2019 08:36:15] Unable to open file (unable to open file: name = 'trained_models.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[11/04/2019 08:36:15] <<< Loading model from trained_models_structure.json' ... >>>
Traceback (most recent call last):
  File "c:\users\think\src\keras-wrapper\keras_wrapper\cnn_model.py", line 169, in loadModel
    model = load_model(model_name + '.h5', custom_objects=custom_objects, compile=compile_model)
  File "c:\users\think\src\keras\keras\engine\saving.py", line 446, in load_wrapper
    return load_function(*args, **kwargs)
  File "c:\users\think\src\keras\keras\engine\saving.py", line 534, in load_model
    h5dict = H5Dict(filepath, 'r')
  File "c:\users\think\src\keras\keras\utils\io_utils.py", line 196, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\think\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\think\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'trained_models.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample_ensemble.py", line 62, in <module>
    sample_ensemble(args, params)
  File "C:\Users\think\Desktop\nmt-keras-master\nmt_keras\apply_model.py", line 39, in sample_ensemble
    models = [loadModel(m, -1, full_path=True) for m in args.models]
  File "C:\Users\think\Desktop\nmt-keras-master\nmt_keras\apply_model.py", line 39, in <listcomp>
    models = [loadModel(m, -1, full_path=True) for m in args.models]
  File "c:\users\think\src\keras-wrapper\keras_wrapper\cnn_model.py", line 174, in loadModel
    model = model_from_json(open(model_name + '_structure.json').read(), custom_objects=custom_objects)
FileNotFoundError: [Errno 2] No such file or directory: 'trained_models_structure.json'

**Comment by lvapeab** [comment]
Hi,
you are passing to the script the folders. You need to specify the dataset, the model and the text to translate. Something like:

```
python sample_ensemble.py --models trained_models/EuTrans_enes_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001 --dataset datasets/Dataset_EuTrans_enes.pkl --text examples/EuTrans/test.en
```

Cheers

**Comment by RookieCXL** [comment]
But after I trained this model ，the ‘trained_models_structure.json’ did‘t exists in   “nmt-keras-master\trained_models\EuTrans\”

**Comment by RookieCXL** [comment]
when training,there are just the .pkl file  or the .h5 in trained_models\EuTrans\, there was no ‘trained_models_structure.json’
[12/04/2019 11:00:03] <<< Predicting outputs of val set >>>
Sampling 100/100  -  ETA: 0s
 Total cost of the translations: 8.595118        Average cost of the translations: 0.085951
The sampling took: 5.842376 secs (Speed: 0.058424 sec/sample)

[12/04/2019 11:00:09] Prediction output 0: target_text (text)
[12/04/2019 11:00:09] Decoding beam search prediction ...
[12/04/2019 11:00:09] Using heuristic 0
[12/04/2019 11:00:09] Evaluating on metric coco
[12/04/2019 11:00:09] Computing coco scores on the val split...
[12/04/2019 11:00:09] Bleu_1: 0.9999999999979755
[12/04/2019 11:00:09] Bleu_2: 0.9999999999979186
[12/04/2019 11:00:09] Bleu_3: 0.9999999999978519
[12/04/2019 11:00:09] Bleu_4: 0.999999999997773
[12/04/2019 11:00:09] CIDEr: 9.95
[12/04/2019 11:00:09] ROUGE_L: 1.0
[12/04/2019 11:00:09] Done evaluating on metric coco
[12/04/2019 11:00:09] <<< Saving model to trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001//epoch_40 ... >>>
[12/04/2019 11:00:09] <<< Model saved >>>
[12/04/2019 11:00:09] ---bad counter: 10/10
[12/04/2019 11:00:09] ---epoch 40: early stopping. Best Bleu_4 found at epoch 30: 1.000000

**Comment by RookieCXL** [comment]
while decoding, there was no' trained_models_structure.json 'found.

**Comment by lvapeab** [comment]
You should have a `trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001//epoch_40.h5`

For using it, you should execute:

```
python sample_ensemble.py --models trained_models/EuTrans_enes_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_40 --dataset datasets/Dataset_EuTrans_enes.pkl --text examples/EuTrans/test.en
```

**Comment by RookieCXL** [comment]
Thanks，It works。
