### ISSUE TITLE
Error while Using Validation data in fit generator

### ISSUE THREAD

**Issue by KushalDave** [lvapeab/nmt-keras#109]
Hi,

I am using the Translation model class in model_zoo to create my own model and run through my data (hvd is the horovod object):

```
nmt_model = TranslationModel(parameters,
		model_type=parameters['MODEL_TYPE'],
		 verbose=parameters['VERBOSE'],
		model_name=parameters['MODEL_NAME'],
		store_path=parameters['STORE_PATH'],
		set_optimizer=set_optimizer,
		clear_dirs=clear_dirs)

```
```
         training_generator = DataGeneratorAttention(TrainX, 
			train_batch_count // hvd.size(), 
			TrainY, 
			FLAGS.batch_size, 
			parameters['MAX_INPUT_TEXT_LEN'], 
			parameters['INPUT_VOCABULARY_SIZE'],
			parameters['MAX_OUTPUT_TEXT_LEN'],
			parameters['OUTPUT_VOCABULARY_SIZE'])
```

```
	validation_generator = DataGeneratorAttention(TestX, 
					TestY, 
					test_batch_count, 
					FLAGS.batch_size, 
                                        parameters['MAX_INPUT_TEXT_LEN'], 
					parameters['INPUT_VOCABULARY_SIZE'],
					parameters['MAX_OUTPUT_TEXT_LEN'],	 
                                       parameters['OUTPUT_VOCABULARY_SIZE'])
```

`mymod.fit_generator(generator=training_generator, validation_data=validation_generator, steps_per_epoch=train_batch_count // hvd.size(),validation_steps= test_batch_count// hvd.size(), workers=FLAGS.num_workers, verbose=2, epochs=FLAGS.max_epoch_num, callbacks=callbacks, use_multiprocessing=FLAGS.use_multiprocessing)`

My data generator outputs the follwing tuple (as expected by the model):
```
	def __data_generation(self, index):
		X1= np.asarray(self.X[0])
		X1 = X1[index*self.batch_size:(index+1)*self.batch_size,:]
		Xm = (self.X[1])[index*self.batch_size:(index+1)*self.batch_size,:]
		Y1 = self.Y[index*self.batch_size:(index+1)*self.batch_size,:]
		#Ym = (self.Y[1])[index*self.batch_size:(index+1)*self.batch_size,:]
		#X = pad_sequences(X, maxlen=self.src_max_length, padding='post')
		#Y = pad_sequences(Y, maxlen=self.tar_max_length, padding='post')
		#y = np.zeros(shape=(self.batch_size, self.tar_max_length, self.tar_vocab_size), dtype=np.uint8)
		y = np.zeros(Y1.shape + (self.tar_vocab_size,), dtype=np.uint8)
		y[self.__all_idx(Y1, 2)] = 1
		Xr = [0,0];
		Xr = [0 for i in range(2)]  # multiple inputs
		Xr[0] = np.asarray(X1, dtype=np.uint16)
		Xr[1]= np.asarray(Xm, dtype='int8')
		#Yr = [0 for i in range(2)]  # multiple inputs
		#Yr[0] = np.asarray(Y1, dtype=np.uint16)
		#Yr[1]= np.asarray(Ym, dtype='int8')
		return Xr, y
```

The above snippet runs fine ( batches get trained and i have the trained model)  when I just use training data and no validation data (that is, remove the validation_data param from fit generator).  When supplying the validation parameters, i get the following error:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/apprunner/.working/runtime/app/keras/utils/data_utils.py", line 564, in _run
    sequence = list(range(len(self.sequence)))
TypeError: only integer scalar arrays can be converted to a scalar index
```

Do you know what could be wrong? I have checked the validation data and done some basic sanity check and the data looks fine to me.

**Comment by KushalDave** [comment]
It was an issue unrelated to the nmt-keras library. Issue where I swap the TrainY and batchcount variables.
