### ISSUE TITLE
run nmt_model.trainNet(dataset, training_params) appearing error

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#14]
`>>> nmt_model.trainNet(dataset, training_params)`
```
ERROR (theano.gof.opt): SeqOptimizer apply <theano.scan_module.scan_opt.PushOutScanOutput object at 0x7f90fa72e6d0>
[13/06/2017 15:41:30] SeqOptimizer apply <theano.scan_module.scan_opt.PushOutScanOutput object at 0x7f90fa72e6d0>
ERROR (theano.gof.opt): Traceback:
[13/06/2017 15:41:30] Traceback:

ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 685, in apply
    node = self.process_node(fgraph, node)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 745, in process_node
    node, args)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 854, in push_out_inner_vars
    add_as_nitsots)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 906, in add_nitsot_outputs
    reason='scanOp_pushout_output')
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/toolbox.py", line 365, in replace_all_validate
    fgraph.validate()
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/toolbox.py", line 256, in validate_
    ret = fgraph.execute_callbacks('validate')
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/fg.py", line 589, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/toolbox.py", line 422, in validate
    raise theano.gof.InconsistencyError("Trying to reintroduce a removed node")
InconsistencyError: Trying to reintroduce a removed node

[13/06/2017 15:41:30] Traceback (most recent call last):
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 685, in apply
    node = self.process_node(fgraph, node)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 745, in process_node
    node, args)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 854, in push_out_inner_vars
    add_as_nitsots)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 906, in add_nitsot_outputs
    reason='scanOp_pushout_output')
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/toolbox.py", line 365, in replace_all_validate
    fgraph.validate()
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/toolbox.py", line 256, in validate_
    ret = fgraph.execute_callbacks('validate')
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/fg.py", line 589, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/home/hanyaqian/anaconda2/lib/python2.7/site-packages/theano/gof/toolbox.py", line 422, in validate
    raise theano.gof.InconsistencyError("Trying to reintroduce a removed node")
InconsistencyError: Trying to reintroduce a removed node


[13/06/2017 15:44:00] Evaluating only every 2 epochs

[13/06/2017 15:44:00] <<< Saving model to trained_models/tutorial_model//epoch_1 ... >>>
[13/06/2017 15:44:00] <<< Saving model_init to trained_models/tutorial_model//epoch_1_structure_init.json... >>>
[13/06/2017 15:44:00] <<< Saving model_next to trained_models/tutorial_model//epoch_1_structure_next.json... >>>
[13/06/2017 15:44:00] <<< Model saved >>>
[13/06/2017 15:45:55] 
<<< Predicting outputs of val set >>>
Sampling 100/100  -  ETA: 0s 
 Total cost of the translations: 96.768829 	 Average cost of the translations: 0.967688
The sampling took: 22.351837 secs (Speed: 0.223518 sec/sample)
[13/06/2017 15:46:17] Decoding beam search prediction ...
[13/06/2017 15:46:17] Evaluating on metric coco
[13/06/2017 15:46:25] Computing coco scores on the val split...
[13/06/2017 15:46:25] Bleu_1: 0.943993237198
[13/06/2017 15:46:25] Bleu_2: 0.927467567158
[13/06/2017 15:46:25] Bleu_3: 0.91578598517
[13/06/2017 15:46:25] Bleu_4: 0.904647321576
[13/06/2017 15:46:25] CIDEr: 8.86298033527
[13/06/2017 15:46:25] METEOR: 0.620198973276
[13/06/2017 15:46:25] ROUGE_L: 0.959634757281
[13/06/2017 15:46:25] TER: 0.0556680161943
[13/06/2017 15:46:25] Done evaluating on metric coco
[13/06/2017 15:46:25] <<< Progress plot saved in trained_models/tutorial_model//epoch_2.jpg >>>
[13/06/2017 15:46:25] <<< Saving model to trained_models/tutorial_model//epoch_2 ... >>>
[13/06/2017 15:46:25] <<< Saving model_init to trained_models/tutorial_model//epoch_2_structure_init.json... >>>
[13/06/2017 15:46:25] <<< Saving model_next to trained_models/tutorial_model//epoch_2_structure_next.json... >>>
[13/06/2017 15:46:25] <<< Model saved >>>

[13/06/2017 15:46:25] <<< Saving model to trained_models/tutorial_model//epoch_2 ... >>>
[13/06/2017 15:46:25] <<< Saving model_init to trained_models/tutorial_model//epoch_2_structure_init.json... >>>
[13/06/2017 15:46:25] <<< Saving model_next to trained_models/tutorial_model//epoch_2_structure_next.json... >>>
[13/06/2017 15:46:25] <<< Model saved >>>
```

Hi @lvapeab 

The above is some log information. What is wrong with that? Looks like this error is not fatal.

**Comment by lvapeab** [comment]
Hi, 
this is a Theano error that appeared with the new backend (see https://github.com/Theano/Theano/issues/5994). It appears when using scan with masks in Keras ([here](https://github.com/MarcBS/keras/blob/master/keras/backend/theano_backend.py#L1126-L1134)).

As you say, it is not a critical error and the model keeps working and training. Nevertheless, it is cumbersome. If you use the Theano flag `optimizer_excluding=scanOp_pushout_output`, the errors are gone (although it may slow down computations).

**Comment by hanyaqian** [comment]
Hi @lvapeab 

I understand, thank you very much for your answer.

**Comment by miradel51** [comment]
Why appear such a problem？ How can we avoid？ If we use Theano flag optimizer_excluding=scanOp_pushout_output， why it may be slow down the speed of computation？

**Comment by lvapeab** [comment]
I haven't investigated so much about this issue. Refer to the aforementioned Theano issue for deeper insights. Since using these flag we don't apply an optimization, there may happen a slow down. Nevertheless, I have noticed almost no difference between enabling/disabling that flag.
