### ISSUE TITLE
another little problem in 3_decoding_tutorial

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#16]
Hi @lvapeab 

there is some error when i run 

` >>>filepath = nmt_model.model_path+'/' + 'test' + '_sampling.pred'  # results file`
` >>>import utils`
` >>> utils.read_write.list2file(filepath, predictions)`
` Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'read_write'
`

Should i use the module of keras_wrapper?

`>>> import keras_wrapper`
`>>> keras_wrapper.extra.read_write.list2file(filepath, predictions)`
`>>>`

**Comment by lvapeab** [comment]
Argh! You're right. Yes, I all utils functions to keras_wrapper.
I've just updated the notebook, though I haven't tested it. 
Thanks again!

**Comment by hanyaqian** [comment]
Hi @lvapeab 

It seems that I have found the last question in `3_decoding_tutorial`, but I do not know how to solve it.

`>>> metrics = utils.evaluation.select[metric](pred_list=predictions,
                                           verbose=1,
                                           extra_vars=extra_vars,
                                           split='test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'evaluation'
`

**Comment by lvapeab** [comment]
Hi, 
in my last update to that notebook, I also fixed that. You should do something like:

```python
from keras_wrapper.extra.evaluation import select
metric = 'coco'
metrics = select[metric](pred_list=predictions,
                                          verbose=1,
                                          extra_vars=extra_vars,
                                          split='test')
```

**Comment by hanyaqian** [comment]
When I did that, there was a new question.

`>>> metrics = select[metric](pred_list=predictions,
                                           verbose=1,
                                           extra_vars=extra_vars,
                                           split='test')
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/keras_wrapper/extra/evaluation.py", line 44, in get_coco_score
  File "build/bdist.linux-x86_64/egg/keras_wrapper/extra/evaluation.py", line 44, in <dictcomp>
AttributeError: 'list' object has no attribute 'strip'
`

**Comment by lvapeab** [comment]
Hello, 
I'm not sure about this error. I have just executed the notebook and everything seems to be ok.
What do you have in your variable `predictions`?

**Comment by hanyaqian** [comment]
`>>> print predictions`

` [30, 26, 28, 98, 11, 5, 23, 31, 79, 8, 10, 4, 0]
 [17, 9, 72, 3, 46, 13, 5, 23, 63, 37, 31, 13, 22, 8, 10, 6, 0]
 [12, 17, 48, 3, 35, 5, 29, 3, 56, 83, 42, 4, 0]
 [12, 32, 3, 44, 8, 35, 5, 4, 0] [40, 18, 26, 42, 20, 141, 4, 0]
 [12, 49, 52, 42, 20, 3, 55, 51, 70, 19, 7, 89, 4, 0]
 [16, 9, 88, 7, 24, 13, 5, 23, 79, 79, 65, 13, 18, 8, 10, 6, 0]
 [10, 40, 18, 26, 20, 3, 55, 11, 70, 4, 0]
 [16, 9, 40, 22, 26, 20, 3, 55, 11, 65, 6, 0]
 [17, 9, 39, 128, 18, 26, 42, 20, 3, 55, 51, 66, 8, 10, 6, 0]
 [16, 9, 136, 7, 41, 19, 7, 46, 6, 0]
 [33, 9, 104, 103, 7, 24, 13, 18, 8, 10, 6, 0]
 [15, 32, 3, 36, 5, 8, 10, 4, 0] [15, 49, 52, 86, 20, 57, 19, 7, 93, 4, 0]
 [12, 17, 48, 9, 11, 30, 27, 41, 11, 27, 5, 8, 10, 4, 0]
 [12, 43, 3, 38, 13, 129, 376, 4, 0] [30, 27, 41, 11, 7, 5, 8, 10, 4, 0]
 [12, 32, 11, 62, 3, 36, 5, 13, 86, 4, 0]]
`

something like above

**Comment by lvapeab** [comment]
Ok. You need to decode your predictions before evaluating. I.e., transform them from indices to words. 
Try to follow the (updated) tutorial from box 6 (In [6]:).

**Comment by hanyaqian** [comment]
@lvapeab, it works ,Thanks. >_<
