### ISSUE TITLE
Error in running main.py without modification

### ISSUE THREAD

**Issue by bughunter99** [lvapeab/nmt-keras#26]
Hi,
I wanted to run main.py, but I got a error like below:
The position the error happened is 
ctx_mean = MaskedMean()(annotations)
where it might initialize by means of a MLP.

Anyone knows solution of this?
Thanks.

Using TensorFlow backend.
[02/08/2017 16:19:57] Log file (/home/a/.picloud/cloud.log) opened
[02/08/2017 16:19:57] Running training.
[02/08/2017 16:19:57] Building EuTrans_esen dataset
[02/08/2017 16:19:57] 	Applying tokenization function: "tokenize_none".
[02/08/2017 16:19:57] Creating vocabulary for data with id 'target_text'.
[02/08/2017 16:19:57] 	 Total: 513 unique words in 9900 sentences with a total of 98304 words.
[02/08/2017 16:19:57] Creating dictionary of all words
[02/08/2017 16:19:57] Loaded "train" set outputs of type "text" with id "target_text" and length 9900.
[02/08/2017 16:19:57] Loaded "train" set inputs of type "file-name" with id "raw_target_text".
[02/08/2017 16:19:57] 	Applying tokenization function: "tokenize_none".
[02/08/2017 16:19:57] Loaded "val" set outputs of type "text" with id "target_text" and length 100.
[02/08/2017 16:19:57] Loaded "val" set inputs of type "file-name" with id "raw_target_text".
[02/08/2017 16:19:57] 	Applying tokenization function: "tokenize_none".
[02/08/2017 16:19:57] Loaded "test" set outputs of type "text" with id "target_text" and length 2996.
[02/08/2017 16:19:57] Loaded "test" set inputs of type "file-name" with id "raw_target_text".
[02/08/2017 16:19:57] 	Applying tokenization function: "tokenize_none".
[02/08/2017 16:19:57] Creating vocabulary for data with id 'source_text'.
[02/08/2017 16:19:57] 	 Total: 686 unique words in 9900 sentences with a total of 96172 words.
[02/08/2017 16:19:57] Creating dictionary of all words
[02/08/2017 16:19:57] Loaded "train" set inputs of type "text" with id "source_text" and length 9900.
[02/08/2017 16:19:57] 	Applying tokenization function: "tokenize_none".
[02/08/2017 16:19:57] 	Reusing vocabulary named "target_text" for data with id "state_below".
[02/08/2017 16:19:57] Loaded "train" set inputs of type "text" with id "state_below" and length 9900.
[02/08/2017 16:19:57] Loaded "train" set inputs of type "file-name" with id "raw_source_text".
[02/08/2017 16:19:57] 	Applying tokenization function: "tokenize_none".
[02/08/2017 16:19:57] Loaded "val" set inputs of type "text" with id "source_text" and length 100.
[02/08/2017 16:19:57] Loaded "val" set inputs of type "ghost" with id "state_below" and length 100.
[02/08/2017 16:19:57] Loaded "val" set inputs of type "file-name" with id "raw_source_text".
[02/08/2017 16:19:57] 	Applying tokenization function: "tokenize_none".
[02/08/2017 16:19:57] Loaded "test" set inputs of type "text" with id "source_text" and length 2996.
[02/08/2017 16:19:57] Loaded "test" set inputs of type "ghost" with id "state_below" and length 2996.
[02/08/2017 16:19:57] Loaded "test" set inputs of type "file-name" with id "raw_source_text".
[02/08/2017 16:19:57] Keeping 1 captions per input on the val set.
[02/08/2017 16:19:57] Samples reduced to 100 in val set.
[02/08/2017 16:19:57] <<< Saving Dataset instance to datasets//Dataset_EuTrans_esen.pkl ... >>>
[02/08/2017 16:19:57] <<< Dataset instance saved >>>
[02/08/2017 16:19:57] <<< Building GroundHogModel Translation_Model >>>
Traceback (most recent call last):
  File "/home/a/workspace/test/nmt/nmt-keras-master/main.py", line 409, in <module>
    train_model(parameters, args.dataset)
  File "/home/a/workspace/test/nmt/nmt-keras-master/main.py", line 79, in train_model
    store_path=params['STORE_PATH'])
  File "/home/a/workspace/test/nmt/nmt-keras-master/model_zoo.py", line 113, in __init__
    eval('self.' + model_type + '(params)')
  File "<string>", line 1, in <module>
  **File "/home/a/workspace/test/nmt/nmt-keras-master/model_zoo.py", line 344, in GroundHogModel
    ctx_mean = MaskedMean()(annotations)**
  File "/home/a/다운로드/src/keras/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/a/다운로드/src/keras/keras/layers/core.py", line 1085, in call
    return K.mean(mask[:, :, None] * x, axis=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 829, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 614, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype bool for Tensor with dtype float32: 'Tensor("annotations_batch_normalization/add_4:0", shape=(?, ?, 128), dtype=float32)'

**Comment by lvapeab** [comment]
Hi, 
it seems like you are using the tensorflow backend. This library is only tested for the Theano backend. Switch your Keras backend to Theano. 

Moreover, make sure you use [our Keras fork](https://github.com/MarcBS/keras)
Cheers

**Comment by bughunter99** [comment]
Thanks, it works.
