### ISSUE TITLE
error in the master version

### ISSUE THREAD

**Issue by lagleki** [lvapeab/nmt-keras#27]
1. `python main.py` (no modifications to config.py)

```
...
[28/09/2017 08:00:38] Evaluating on metric coco
Traceback (most recent call last):
  File "main.py", line 410, in <module>
    train_model(parameters, args.dataset)
  File "main.py", line 161, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/home/user/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 737, in trainNet
    self.__train(ds, params)
  File "/home/user/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 928, in __train
    initial_epoch=params['epoch_offset'])
  File "/home/user/nmt-keras/keras/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/user/nmt-keras/keras/keras/engine/training.py", line 1947, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/user/nmt-keras/keras/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/user/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 197, in on_epoch_end
    self.evaluate(epoch, counter_name='epoch')
  File "/home/user/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 346, in evaluate
    split=s)
  File "/home/user/nmt-keras/src/keras-wrapper/keras_wrapper/extra/evaluation.py", line 55, in get_coco_score
    scorers.append((Meteor(language=extra_vars['language']), "METEOR"))
  File "/home/user/nmt-keras/coco-caption/pycocoevalcap/meteor/meteor.py", line 21, in __init__
    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=d)
  File "/home/user/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/user/miniconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Solution: write out JAVA_HOME manually, check java jre installation

2. errors in h5py

Relevant to https://github.com/fchollet/keras/issues/3426

Solution: uninstall h5py, `pip install h5py` again.

**Comment by lvapeab** [comment]
Hello,

it seems that you have a problem with the evaluation, more precisely with the Meteor module. Please, make sure you have [the coco-caption ](https://github.com/lvapeab/coco-caption) properly installed with the [Meteor paraphrase data](https://github.com/lvapeab/coco-caption/tree/master/pycocoevalcap/meteor/data) available in the right folder.

Cheers.
