### ISSUE TITLE
can't train with multiple encoder/decoder layers 

### ISSUE THREAD

**Issue by yftah89** [lvapeab/nmt-keras#30]
When I change the config file in the following way:
N_LAYERS_ENCODER = 2
N_LAYERS_DECODER = 2
(all the rest is kept the same)

I get the following : 

Traceback (most recent call last):
  File "main.py", line 434, in <module>
    train_model(parameters, args.dataset)
  File "main.py", line 81, in train_model
    store_path=params['STORE_PATH'])
  File "/home/syftah@st.technion.ac.il/nmt-keras/model_zoo.py", line 113, in __init__
    eval('self.' + model_type + '(params)')
  File "<string>", line 1, in <module>
  File "/home/syftah@st.technion.ac.il/nmt-keras/model_zoo.py", line 468, in AttentionRNNEncoderDecoder
    current_rnn_output = shared_proj_h_list[-1](current_rnn_input)
  File "/home/syftah@st.technion.ac.il/nmt-keras/src/keras/keras/legacy/layers.py", line 969, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/home/syftah@st.technion.ac.il/nmt-keras/src/keras/keras/engine/topology.py", line 561, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/syftah@st.technion.ac.il/nmt-keras/src/keras/keras/engine/topology.py", line 460, in assert_input_compatibility
    str(K.ndim(x)))

This didn't happened to me with the same code I downloaded two months ago, maybe some new problematic update you have done recently?

I'm sorry for bothering you with all my questions, but I'm promise to mention you in my acknowledgments section if my article will be published :)

**Comment by lvapeab** [comment]
Hello,

I've just pushed  a fix for it (https://github.com/MarcBS/keras/commit/3b50f10630a5f5587294b9c6209357e8f76c82f6). You should update Keras.

Thank you for detecting it and good luck with your article! ;)
