### ISSUE TITLE
sample_ensemble.py stopped working 

### ISSUE THREAD

**Issue by yftah89** [lvapeab/nmt-keras#33]
Suddenly I cant run sample_ensemble.py, its runs into error, does it works for you?

**Comment by lvapeab** [comment]
Hi,

yes, it works properly for me. What is that error?

**Comment by yftah89** [comment]
I'm having some weird issue but its probably happens just in my environment so you can close this one as well :)

**Comment by hiteshvaidya** [comment]
```
Exception happened during processing of request from ('127.0.0.1', 57770)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "sample_server.py", line 49, in do_GET
    learn = eval(learn)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by hiteshvaidya** [comment]
could you please help me @lvapeab ?
