### ISSUE TITLE
NoneType object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by shrutihal** [lvapeab/nmt-keras#34]
I am following the https://nmt-keras.readthedocs.io/en/latest/tutorial.html#dataset-tutorial. Everything runs just fine until I reach 'keep_n_captions(ds, repeat=1, n=1, set_names=['val'])'. Error is: 

[26/01/2018 11:37:44] Keeping 1 captions per input on the val set.
Traceback (most recent call last):
  File "/Users/name/install/nmt-keras/datasetspaneng.py", line 81, in <module>
    keep_n_captions(ds, repeat=1, n=1, set_names=['val'])
  File "/Users/name/install/nmt-keras/data_engine/prepare_data.py", line 272, in keep_n_captions
    for i in range(0, n_samples, repeat):
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by lvapeab** [comment]
Hello @shrutihal ,

I cannot reproduce your error. Are you sure you have successfully followed all previous steps from the tutorial?
