### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yanmengqi** [lvapeab/nmt-keras#38]
Epoch 1/500
198/198 [==============================] - 156s 789ms/step - loss: 6.4545

[12/03/2018 19:22:10] <<< Predicting outputs of val set >>>
Sampling 100/100  -  ETA: 0s 
 Total cost of the translations: 851.135783 	 Average cost of the translations: 8.511358
The sampling took: 12.092935 secs (Speed: 0.120929 sec/sample)

[12/03/2018 19:22:22] Prediction output 0: target_text (text)
[12/03/2018 19:22:22] Decoding beam search prediction ...
[12/03/2018 19:22:22] Using heuristic 0
[12/03/2018 19:22:22] Evaluating on metric coco
Traceback (most recent call last):
  File "main.py", line 419, in <module>
    train_model(parameters, args.dataset)
  File "main.py", line 164, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/home/yanmengqi/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 813, in trainNet
    self.__train(ds, params)
  File "/home/yanmengqi/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 1049, in __train
    initial_epoch=params['epoch_offset'])
  File "/home/yanmengqi/nmt-keras/src/keras/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yanmengqi/nmt-keras/src/keras/keras/engine/training.py", line 2363, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/yanmengqi/nmt-keras/src/keras/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/yanmengqi/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 264, in on_epoch_end
    self.evaluate(epoch, counter_name='epoch')
  File "/home/yanmengqi/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 470, in evaluate
    split=s)
  File "/home/yanmengqi/nmt-keras/src/keras-wrapper/keras_wrapper/extra/evaluation.py", line 55, in get_coco_score
    scorers.append((Meteor(language=extra_vars['language']), "METEOR"))
  File "/home/yanmengqi/nmt-keras/src/coco-caption/pycocoevalcap/meteor/meteor.py", line 20, in __init__
    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=d)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I have faced this problem,and I have searched but have nothing.Can you tell me how to solve this problem?
我遇到了这个问题，请问怎样解决这个问题？

**Comment by lvapeab** [comment]
Hello,

it seems you need to download the [Meteor paraphrases](https://github.com/lvapeab/coco-caption/tree/master/pycocoevalcap/meteor/data) and place it in your meteor folder (`/home/yanmengqi/nmt-keras/src/coco-caption/pycocoevalcap/meteor/data`).

**Comment by yanmengqi** [comment]
@lvapeab No ,I have checked this dictionary,those files is exist.This problem is still existing.

**Comment by lvapeab** [comment]
Do you have java installed?

**Comment by yanmengqi** [comment]
@lvapeab No,Does it need a java development kit?

**Comment by lvapeab** [comment]
If you want to evaluate on Meteor and TER, yes, as required the [Coco-caption](https://github.com/lvapeab/coco-caption) evaluation package.  I should probably mention it at the README file.

If you don't want to install java, you can comment the lines [50](https://github.com/lvapeab/multimodal_keras_wrapper/blob/master/keras_wrapper/extra/evaluation.py#L50) and [55-56](https://github.com/lvapeab/multimodal_keras_wrapper/blob/661f7b6fb847484acfcbaa74d06c2242bd126b63/keras_wrapper/extra/evaluation.py#L54-L55) in the evaluation file from the keras wrapper (in `/home/yanmengqi/nmt-keras/src/keras-wrapper/keras_wrapper/extra/evaluation.py`).

**Comment by yanmengqi** [comment]
Ok,I think i have know the reason.Thank you!
