### ISSUE TITLE
AttributeError: 'TranslationModel' object has no attribute 'tokenize_none'

### ISSUE THREAD

**Issue by yanmengqi** [lvapeab/nmt-keras#45]
Hello,I have used nmt-keras trained an Chinese-English model.
Now,I 'd like to use you demo-web components to show it at a web page.
I am using the interactive_NMT branch of nmt-keras,but when I try to started it at the readme.md ,at this step,there appeared a problem
I try to run this code:
`python ./sample_server.py --dataset datasets/Dataset.pkl --port=8888
        --config trained_models/config.pkl --models trained_models/update_15000`

there is the wrong code:
`  from ._conv import register_converters as _register_converters
Using Theano backend.
[17/04/2018 10:46:46] Using NumPy C-API based implementation for BLAS functions.
[17/04/2018 10:46:47] CACHEDIR=/home/yanmengqi/.cache/matplotlib
[17/04/2018 10:46:47] Using fontManager instance from /home/yanmengqi/.cache/matplotlib/fontList.json
[17/04/2018 10:46:47] backend agg version v2.2
[17/04/2018 10:46:47] Loading parameters from trained_models/config.pkl
[17/04/2018 10:46:47] <<< Loading Dataset instance from datasets/Dataset.pkl ... >>>
[17/04/2018 10:46:47] <<< Dataset instance loaded >>>
Traceback (most recent call last):
  File "./sample_server.py", line 469, in <module>
    main()
  File "./sample_server.py", line 349, in main
    tokenize_f = eval('dataset.' + params.get('TOKENIZATION_METHOD', 'tokenize_none'))
  File "<string>", line 1, in <module>
AttributeError: 'TranslationModel' object has no attribute 'tokenize_none'`

**Comment by lvapeab** [comment]
You need to modify that code so that it points to the dataset object you used to train your model and the config and model update you want for performing the translations.

**Comment by yanmengqi** [comment]
I hava already solved this problem.but now I have faced a new problom.
when I tried run this code ,there is a new wrong bug appeared.
there is the wrong code.

`Using Theano backend.
[21/04/2018 19:24:40] Using NumPy C-API based implementation for BLAS functions.
[21/04/2018 19:24:40] CACHEDIR=/home/yanmengqi/.cache/matplotlib
[21/04/2018 19:24:40] Using fontManager instance from /home/yanmengqi/.cache/matplotlib/fontList.json
[21/04/2018 19:24:40] backend agg version v2.2
[21/04/2018 19:24:40] Loading parameters from trained_models/config.pkl
[21/04/2018 19:24:40] <<< Loading Dataset instance from datasets/Dataset.pkl ... >>>
[21/04/2018 19:24:40] <<< Dataset instance loaded >>>
Traceback (most recent call last):
  File "sample_server.py", line 469, in <module>
    main()
  File "sample_server.py", line 352, in main
    dataset.build_moses_tokenizer(language=params['SRC_LAN'])
  File "build/bdist.linux-x86_64/egg/keras_wrapper/dataset.py", line 1559, in build_moses_tokenizer
ImportError: No module named nltk
`

**Comment by yanmengqi** [comment]
Very thank you. I have already solved this problem.
Now I can open the demo-web index.html, but I found that when I use this html page and try to translate some words, there is two problem with it:
First, it's accuracy is very low, when I use nmt-keras to train this model, it's accuracy is good, but now it is very bad.I don't know why.
Second, in the translation text box ,I changed target-language from Genman to Chinese, but now the translation text box is English not Chinese.Maybe there are something wrong with my settings, but I don't know which setting is wrong.

The dataset I used is an Chinese-English text, about 100000 lines, have trained about one month, experienced 60 epochs.

The command I used to start the php servers is as follows:
python sample_server.py --dataset datasets/Dataset.pkl --port=8888 --config trained_models/config.pkl --models trained_models/epoch_31
php -S localhost:8000

**Comment by lvapeab** [comment]
Hi @yanmengqi ,

first of all, a small advice: The demo-web is meant to be just a very simple interface for using the toolkit. I didn't spend (and I don't intend to) so much time on it. Therefore, most things are hardcoded, it's not language responsive, etc, etc. 

But anyway, it should work with your settings.

From your comment, I see three possible sources of problems:

* Make sure the `datasets/Dataset.pkl` is the right dataset file you used to train your model. 
* Try to input English source sentences related to your training data. If the system gets sentences from other domain, it can be very confused.
* Chinese is a tricky language. Make sure you are encoding and decoding it properly in the HTML <-> Python interfaces.

Cheers!
