### ISSUE TITLE
issue trying to perform main.py due to save image.

### ISSUE THREAD

**Issue by lchunleo** [lvapeab/nmt-keras#61]
Hi

 i am currrently using python 3.5.2 to run the main.py. However, i can't get through this issue. It has no issue performing the error score calculation but it seem to break after that. Pls advise. thanks

Just curious, is it possible to get around the issue like disabling display of the image ?

[07/07/2018 01:38:49] Done evaluating on metric coco
[07/07/2018 01:38:49] findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/home/guest/.local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
[07/07/2018 01:38:49] findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=12.0 to DejaVu Sans ('/home/guest/.local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
Traceback (most recent call last):
  File "main.py", line 445, in <module>
    train_model(parameters, args.dataset)
  File "main.py", line 169, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/usr/local/lib/python3.5/dist-packages/Multimodal_Keras_Wrapper-0.8-py3.5.egg/keras_wrapper/cnn_model.py", line 830, in trainNet
  File "/usr/local/lib/python3.5/dist-packages/Multimodal_Keras_Wrapper-0.8-py3.5.egg/keras_wrapper/cnn_model.py", line 1093, in __train
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.2.0-py3.5.egg/keras/legacy/interfaces.py", line 91, in wrapper
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.2.0-py3.5.egg/keras/engine/training.py", line 1488, in fit_generator
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.2.0-py3.5.egg/keras/engine/training_generator.py", line 229, in fit_generator
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.2.0-py3.5.egg/keras/callbacks.py", line 77, in on_epoch_end
  File "/usr/local/lib/python3.5/dist-packages/Multimodal_Keras_Wrapper-0.8-py3.5.egg/keras_wrapper/extra/callbacks.py", line 277, in on_epoch_end
  File "/usr/local/lib/python3.5/dist-packages/Multimodal_Keras_Wrapper-0.8-py3.5.egg/keras_wrapper/extra/callbacks.py", line 521, in evaluate
  File "/usr/local/lib/python3.5/dist-packages/Multimodal_Keras_Wrapper-0.8-py3.5.egg/keras_wrapper/cnn_model.py", line 2990, in plot
  File "/home/guest/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 710, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/guest/.local/lib/python3.5/site-packages/matplotlib/figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/guest/.local/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/home/guest/.local/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 584, in print_jpg
    return background.save(filename_or_obj, format='jpeg', **options)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1675, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3/dist-packages/PIL/JpegImagePlugin.py", line 708, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/usr/lib/python3/dist-packages/PIL/ImageFile.py", line 480, in _save
    e = Image._getencoder(im.mode, e, a, im.encoderconfig)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 431, in _getencoder
    return encoder(mode, *args + extra)
TypeError: integer argument expected, got float

**Comment by lchunleo** [comment]
i realize i need to update PIL to python3.
