### ISSUE TITLE
Nmt-keras breaking due to dependencies changing

### ISSUE THREAD

**Issue by howlinghuffy** [lvapeab/nmt-keras#69]
It seems that nmt-keras is now breaking when you install the latest requirements.txt.  Nmt-keras was working fine for me with a version that I built a few days ago, but now even the example main.py is failing when evaluating the epoch.

From looking at the trace, it seems like it may be an issue in the keras_wrapper (it seems there was a pretty major change to this dependancy in the last 24 hours).  Having a hard time tracking it down though.

Is anyone else having this issue? Also, should we consider locking the dependency versions in the requirements file so this doesn't happen in future?

Below is the traceback that occurs when I run main.py with the latest requirements installed:

`[27/08/2018 06:44:32] <<< Saving model_init to trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001//epoch_1_structure_init.json... >>>
[27/08/2018 06:44:32] <<< Saving model_next to trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001//epoch_1_structure_next.json... >>>
[27/08/2018 06:44:32] <<< Model saved >>>

[27/08/2018 06:44:32] <<< Predicting outputs of val set >>>
Traceback (most recent call last):
  File "main.py", line 445, in <module>
    train_model(parameters, args.dataset)
  File "main.py", line 169, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/src/src/keras-wrapper/keras_wrapper/cnn_model.py", line 834, in trainNet
    self.__train(ds, params)
  File "/src/src/keras-wrapper/keras_wrapper/cnn_model.py", line 1104, in __train
    initial_epoch=params['epoch_offset'])
  File "/src/src/keras/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/src/src/keras/keras/engine/training.py", line 1485, in fit_generator
    initial_epoch=initial_epoch)
  File "/src/src/keras/keras/engine/training_generator.py", line 247, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/src/src/keras/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/src/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 279, in on_epoch_end
    self.evaluate(epoch, counter_name='epoch')
  File "/src/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 314, in evaluate
    predictions_all = self.model_to_eval.predictBeamSearchNet(self.ds, params_prediction)[s]
  File "/src/src/keras-wrapper/keras_wrapper/cnn_model.py", line 2183, in predictBeamSearchNet
    return_alphas=params['coverage_penalty'])
  File "/src/src/keras-wrapper/keras_wrapper/cnn_model.py", line 1546, in beam_search
    [probs, prev_out] = self.predict_cond_optimized(X, state_below, params, ii, prev_out)
  File "/src/src/keras-wrapper/keras_wrapper/cnn_model.py", line 1433, in predict_cond_optimized
    out_data = model.predict_on_batch(in_data)
  File "/src/src/keras/keras/engine/training.py", line 1342, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/src/src/keras/keras/backend/tensorflow_backend.py", line 2835, in __call__
    return self._call(inputs)
  File "/src/src/keras/keras/backend/tensorflow_backend.py", line 2804, in _call
    session)
  File "/src/src/keras/keras/backend/tensorflow_backend.py", line 2756, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1414, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1368, in __init__
    session._session, options_ptr, status)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: preprocessed_input:0 is both fed and fetched.
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f6a58359588>>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1398, in __del__
    self._session._session, self._handle, status)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No such callable handle: 140091769661888
`

**Comment by howlinghuffy** [comment]
@lvapeab It seems you made [some major changes](https://github.com/MarcBS/multimodal_keras_wrapper/commit/7e3976169b3380ea75bc1336bf376f2075112ab9) in the past day for the files that seem to be breaking for me, in keras_multimodal_wrapper.  Are you able to shed some light on this issue? Many thanks.

**Comment by lvapeab** [comment]
Hi @howlinghuffy ,

thanks for the catch. Its was a problem with the TF backend of Keras. I've just pushed a fix (https://github.com/MarcBS/keras/commit/246c1155d95a7cabc97a1b72e33d45d6711839d0).

Can you please update your Keras repo and test it again?

**Comment by lvapeab** [comment]
Hi @howlinghuffy ,

yes, definitely. Thanks for the suggestion. I will do it in the upcoming releases :)
