### ISSUE TITLE
Error while replacing Unknown words using Utils - 'str' has no attribute decode('utf-8')

### ISSUE THREAD

**Issue by mohammedayub44** [lvapeab/nmt-keras#70]
Hi,

Any reason why I might be getting this error while its decoding beam search predictions ? Below is the output: 

[01/09/2018 02:35:32] <<< Model saved >>>
[01/09/2018 02:35:32] <<< Predicting outputs of val set >>>
Sampling 100/100  -  ETA: 0s
 Total cost of the translations: 1784.566795     Average cost of the translation                                                                                                 s: 17.845668
The sampling took: 87.721825 secs (Speed: 0.877218 sec/sample)

[01/09/2018 02:37:00] Prediction output 0: target_text (text)
[01/09/2018 02:37:00] Decoding beam search prediction ...
[01/09/2018 02:37:00] Decoding beam search prediction ...
[01/09/2018 02:37:00] Using heuristic 0
Traceback (most recent call last):
  File "main.py", line 445, in <module>
    train_model(parameters, args.dataset)
  File "main.py", line 169, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/home/ubuntu/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", li                                                                                                 ne 832, in trainNet
    self.__train(ds, params)
  File "/home/ubuntu/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", li                                                                                                 ne 1107, in __train
    initial_epoch=params['epoch_offset'])
  File "/home/ubuntu/nmt-keras/src/keras/keras/legacy/interfaces.py", line 91, i                                                                                                 n wrapper
    return func(args, kwargs)
  File "/home/ubuntu/nmt-keras/src/keras/keras/engine/training.py", line 1477, i                                                                                                 n fit_generator
    initial_epoch=initial_epoch)
  File "/home/ubuntu/nmt-keras/src/keras/keras/engine/training_generator.py", li                                                                                                 ne 247, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ubuntu/nmt-keras/src/keras/keras/callbacks.py", line 77, in on_epo                                                                                                 ch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ubuntu/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.p                                                                                                 y", line 277, in on_epoch_end
    self.evaluate(epoch, counter_name='epoch')
  File "/home/ubuntu/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.p                                                                                                 y", line 390, in evaluate
    verbose=self.verbose)
  File "/home/ubuntu/nmt-keras/src/keras-wrapper/keras_wrapper/utils.py", line 9                                                                                                 47, in decode_predictions_beam_search
    verbose=verbose)
File "/home/ubuntu/nmt-keras/src/keras-wrapper/keras_wrapper/utils.py", line 8                                                                                                 83, in replace_unknown_words 
    **UNK_src = UNK_src.decode(utf-8)**
**AttributeError: str object has no attribute decode**

Any help appreciated. 

-Mohammed Ayub

**Comment by lvapeab** [comment]
Fixed (https://github.com/lvapeab/multimodal_keras_wrapper/commit/d236c41f0e56a5edda2882349b2ce1fde865f660). Update the `keras_wrapper`.

**Comment by mohammedayub44** [comment]
Hi,

Not sure if this issue is linked with this. Attaching it however. [https://github.com/lvapeab/nmt-keras/issues/72](url)

-Mohammed Ayub
