### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by parmpreet** [lvapeab/nmt-keras#77]
Hi,
I am trying to setup nmt-keras and train the model using the default values provided. I followed the instructions from https://nmt-keras.readthedocs.io/en/latest/requirements.html#requirements
I am using `Python 2.7.14 :: Anaconda, Inc.`
Macbook pro osx `10.13.6 (17G65)`
latest tensorflow version using `pip install tensorflow`

I am getting the following error while trying to start training:
`[26/09/2018 13:29:49] Preparing optimizer: Adam [LR: 0.001 - LOSS: categorical_crossentropy - CLIP_C 5.0 - CLIP_V  0.0 - LR_OPTIMIZER_DECAY 0.0] and compiling.
[26/09/2018 13:29:49] Starting training!
[26/09/2018 13:29:49] <<< Training model >>>
[26/09/2018 13:29:49] Training parameters: {'reload_epoch': 0, 'wo_da_patch_type': 'whole', 'shuffle': True, 'verbose': 1, 'data_augmentation': False, 'class_weights': None, 'epochs_for_save': 1, 'lr_reducer_exp_base': -0.5, 'lr_gamma': 0.8, 'start_eval_on_epoch': 1, 'n_epochs': 500, 'patience': 10, 'tensorboard': True, 'epoch_offset': 0, 'da_patch_type': 'resize_and_rndcrop', 'mean_substraction': False, 'normalize': True, 'n_gpus': 1, 'n_parallel_loaders': 1, 'each_n_epochs': 1, 'patience_check_split': 'val', 'da_enhance_list': [], 'reduce_each_epochs': False, 'lr_warmup_exp': -1.5, 'lr_reducer_type': 'exponential', 'tensorboard_params': {'batch_size': 50, 'write_grads': False, 'write_images': False, 'label_word_embeddings_with_vocab': True, 'embeddings_metadata': None, 'write_graph': True, 'embeddings_layer_names': ['source_word_embedding', 'target_word_embedding'], 'word_embeddings_labels': ['source_text', 'target_text'], 'embeddings_freq': 1, 'log_dir': 'tensorboard_logs', 'histogram_freq': 0}, 'metric_check': 'Bleu_4', 'start_reduction_on_epoch': 0, 'homogeneous_batches': False, 'batch_size': 50, 'num_iterations_val': None, 'normalization_type': '(-1)-1', 'initial_lr': 0.001, 'lr_half_life': 100, 'lr_decay': None, 'joint_batches': 4, 'maxlen': 50, 'eval_on_epochs': True, 'eval_on_sets': [], 'extra_callbacks': [<keras_wrapper.extra.callbacks.EvalPerformance object at 0x1c23378050>, <keras_wrapper.extra.callbacks.Sample object at 0x1c23378710>]}
[26/09/2018 13:29:49] <<< creating directory trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001//tensorboard_logs ... >>>
2018-09-26 13:29:53.546212: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    train_model(parameters, args.dataset)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/nmt_keras/training.py", line 158, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 886, in trainNet
    self.__train(ds, params)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 1111, in __train
    initial_epoch=params['epoch_offset'])
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/engine/training.py", line 1475, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/engine/training_generator.py", line 94, in fit_generator
    callbacks.set_model(callback_model)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/callbacks.py", line 54, in set_model
    callback.set_model(model)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/callbacks.py", line 771, in set_model
    self.sess = K.get_session()
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/backend/tensorflow_backend.py", line 223, in get_session
    [tf.is_variable_initialized(v) for v in candidate_vars])
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: bidirectional_encoder_LSTM/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0](bidirectional_encoder_LSTM/transpose, bidirectional_encoder_LSTM/ExpandDims_1, bidirectional_encoder_LSTM/ExpandDims_2, bidirectional_encoder_LSTM/concat)]]

Caused by op u'bidirectional_encoder_LSTM/CudnnRNN', defined at:
  File "main.py", line 49, in <module>
    train_model(parameters, args.dataset)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/nmt_keras/training.py", line 81, in train_model
    clear_dirs=clear_dirs)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/nmt_keras/model_zoo.py", line 139, in __init__
    eval('self.' + model_type + '(params)')
  File "<string>", line 1, in <module>
  File "/Users/parm/Documents/learning/nmt/nmt-keras/nmt_keras/model_zoo.py", line 364, in AttentionRNNEncoderDecoder
    merge_mode=params.get('BIDIRECTIONAL_MERGE_MODE', 'concat'))(src_embedding)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/layers/wrappers.py", line 430, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/layers/wrappers.py", line 525, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/layers/cudnn_recurrent.py", line 90, in call
    output, states = self._process_batch(inputs, initial_state)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/layers/cudnn_recurrent.py", line 517, in _process_batch
    is_training=True)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 1544, in __call__
    input_data, input_h, input_c, params, is_training=is_training)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 1435, in __call__
    seed=self._seed)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 922, in _cudnn_rnn
    outputs, output_h, output_c, _ = gen_cudnn_rnn_ops.cudnn_rnn(**args)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 115, in cudnn_rnn
    is_training=is_training, name=name)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/parm/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: bidirectional_encoder_LSTM/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0](bidirectional_encoder_LSTM/transpose, bidirectional_encoder_LSTM/ExpandDims_1, bidirectional_encoder_LSTM/ExpandDims_2, bidirectional_encoder_LSTM/concat)]]`

Could you please help me fix this issue?

**Comment by lvapeab** [comment]
Hi,

it seems you don't have installed `CuDNN`. You can either:

1. Install `CuDNN`: `conda install cudnn`.
2. Rely on the `Keras` implementations of RNNs (LSTM/GRU), setting in the config file the `USE_CUDNN = False`. 

`CuDNN` provides faster GPU implementations of RNNs. But, if you don't have a GPU available, you must follow the second alternative.

Cheers.

**Comment by parmpreet** [comment]
Thanks for quick reply. It seems to have worked but it was failing with the following error
`Traceback (most recent call last):
  File "main.py", line 49, in <module>
    train_model(parameters, args.dataset)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/nmt_keras/training.py", line 158, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 887, in trainNet
    self.__train(ds, params)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 1112, in __train
    initial_epoch=params['epoch_offset'])
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/engine/training.py", line 1475, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/engine/training_generator.py", line 248, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 603, in on_epoch_end
    self.store_function(self.model_to_save, epoch)
  File "/Users/parm/Documents/learning/nmt/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 121, in saveModel
    setattr(model_wrapper, 'multi_gpu_model', backup_multi_gpu_model)
UnboundLocalError: local variable 'backup_multi_gpu_model' referenced before assignment`

I have commented out the following line (line no 121 file: keras-wrapper/keras_wrapper/cnn_model.py ). It is working now.
`setattr(model_wrapper, 'multi_gpu_model', backup_multi_gpu_model)`

**Comment by lvapeab** [comment]
Hi,
thanks for this catch. I fixed the bug. 

I'm closing this issue, since it seems all works.
