### ISSUE TITLE
Quick way to check accuracy of trained model

### ISSUE THREAD

**Issue by qazs** [lvapeab/nmt-keras#78]
Understand I can use score.py, but is there a way to get a general accuracy of a trained model and evaluated against a dataset?

**Comment by lvapeab** [comment]
For obtaining MT metrics, you should use the [utils/evaluate_from_file.py](https://github.com/lvapeab/nmt-keras/blob/master/utils/evaluate_from_file.py) script.

**Comment by qazs** [comment]
Hi @lvapeab ,
Tried running the script but I get this error, I'm evaluating Chinese texts.
```
$ python utils/evaluate_from_file.py -m bleu -l cn -t local/CnTrans/test_mini.cn -r local/CnTrans/test_mini.cn
language cn <codecs.StreamReaderWriter object at 0x00000218B0A76518>
The number of references is 1
[<_io.TextIOWrapper name='local/CnTrans/test_mini.cn' mode='r' encoding='cp936'>]
Traceback (most recent call last):
  File "utils/evaluate_from_file.py", line 118, in <module>
    evaluate_from_file(parser.parse_args())
  File "utils/evaluate_from_file.py", line 93, in evaluate_from_file
    ref, hypothesis = load_textfiles(args.references, hypotheses_file)
  File "utils/evaluate_from_file.py", line 36, in load_textfiles
    raw_refs = list([list(map(str.strip, r)) for r in list(zip(*references))])
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 22: illegal multibyte sequence
(nmt-keras)
```

**Comment by lvapeab** [comment]
It seems there is an encoding problem with your default encoding (`cp936`). I've uploaded a fix for always using `utf-8`. Make `git pull` and run the script again.
