### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by jksignity** [lvapeab/nmt-keras#79]
Hi
I am trying to setup the project,  I made the following change in config.py file
SRC_LAN = 'en'
TRG_LAN = 'es'

and then I ran python main.py, it worked for the 1st epoch, saved the model and then showed the following error: 

[15/10/2018 04:51:28] Prediction output 0: target_text (text)
[15/10/2018 04:51:28] Decoding beam search prediction ...
[15/10/2018 04:51:28] Using heuristic 0
[15/10/2018 04:51:28] Evaluating on metric coco
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    train_model(parameters, args.dataset)
  File "/content/nmt-keras/nmt_keras/training.py", line 159, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/content/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 910, in trainNet
    self.__train(ds, params)
  File "/content/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 1135, in __train
    initial_epoch=params['epoch_offset'])
  File "/content/nmt-keras/src/keras/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/content/nmt-keras/src/keras/keras/engine/training.py", line 1480, in fit_generator
    initial_epoch=initial_epoch)
  File "/content/nmt-keras/src/keras/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/content/nmt-keras/src/keras/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/content/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 280, in on_epoch_end
    self.evaluate(epoch, counter_name='epoch')
  File "/content/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 518, in evaluate
    split=s)
  File "/content/nmt-keras/src/keras-wrapper/keras_wrapper/extra/evaluation.py", line 57, in get_coco_score
    scorers.append((Meteor(language=extra_vars.get('language', 'en')), "METEOR"))
  File "/content/nmt-keras/src/coco-caption/pycocoevalcap/meteor/meteor.py", line 24, in __init__
    env=d)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'
Exception ignored in: <bound method Meteor.__del__ of <pycocoevalcap.meteor.meteor.Meteor object at 0x7f013da0c0b8>>
Traceback (most recent call last):
  File "/content/nmt-keras/src/coco-caption/pycocoevalcap/meteor/meteor.py", line 91, in __del__
    self.lock.acquire()
AttributeError: 'Meteor' object has no attribute 'lock'
Exception ignored in: <bound method Ter.__del__ of <pycocoevalcap.ter.ter.Ter object at 0x7f013db242e8>>
Traceback (most recent call last):
  File "/content/nmt-keras/src/coco-caption/pycocoevalcap/ter/ter.py", line 70, in __del__
    self.ter_p.kill()
AttributeError: 'Ter' object has no attribute 'ter_p'

Could you please help me fix this issue?

**Comment by lvapeab** [comment]
If you want to evaluate on Meteor and TER, you need java, as required by the [Coco-caption](https://github.com/lvapeab/coco-caption) evaluation package. 

If you don't want to install java, you can comment the lines [50](https://github.com/lvapeab/multimodal_keras_wrapper/blob/master/keras_wrapper/extra/evaluation.py#L50) and [55-56](https://github.com/lvapeab/multimodal_keras_wrapper/blob/661f7b6fb847484acfcbaa74d06c2242bd126b63/keras_wrapper/extra/evaluation.py#L54-L55) in the evaluation file from the keras wrapper, in `nmt-keras/src/keras-wrapper/keras_wrapper/extra/evaluation.py`).
