### ISSUE TITLE
Testing Issue

### ISSUE THREAD

**Issue by jksignity** [lvapeab/nmt-keras#80]
So I trained the model using my own small data, it trained for 51 epochs and stopped early because Bleu_4 was found to be 0.000

I have a trained_models folder, and I downloaded it. I ran the following command on server where training occurred and it gave success.

`python sample_ensemble.py --dataset datasets/Dataset_CustomChat_esen.pkl --models trained_models/CustomChat_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_50 --text examples/CustomChat/test.en`

But when I run the same command on local after installing all dependencies from requirements file, I get the following error.

`FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/CustomChat_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_50_structure.json'`

Could you please help me fix this issue?

**Comment by lvapeab** [comment]
Hi @jksignity ,

can you please provide a longer trace of the error?

P.S: If you got 0 points of Bleu, it seems that your model is not properly trained.

**Comment by jksignity** [comment]
Hi @lvapeab 

here's the complete stack trace

```
[16/10/2018 13:08:56] Reading parameters from config.py
[16/10/2018 13:08:56] <<< Cupy not available. Using numpy. >>>
/home/signity/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[16/10/2018 13:08:58] Using an ensemble of 1 models
[16/10/2018 13:08:58] <<< Loading model from trained_models/CustomChat_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_50_Model_Wrapper.pkl ... >>>
[16/10/2018 13:08:58] <<< Loading model from trained_models/CustomChat_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_50.h5 ... >>>
[16/10/2018 13:09:06] softmax() got an unexpected keyword argument 'axis'
[16/10/2018 13:09:06] <<< Loading model from trained_models/CustomChat_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_50_structure.json' ... >>>
Traceback (most recent call last):
  File "/projects/nmt/nmt-keras-master/src/keras-wrapper/keras_wrapper/cnn_model.py", line 165, in loadModel
    model = load_model(model_name + '.h5', custom_objects=custom_objects, compile=compile_model)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/layers/__init__.py", line 60, in deserialize
    printable_module_name='layer')
  File "/projects/nmt/nmt-keras-master/src/keras/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/projects/nmt/nmt-keras-master/src/keras/keras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/legacy/layers.py", line 514, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/layers/recurrent.py", line 6766, in call
    pos_extra_outputs_states=[2, 3])
  File "/projects/nmt/nmt-keras-master/src/keras/keras/backend/tensorflow_backend.py", line 3108, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/layers/recurrent.py", line 6839, in step
    attention_mode=self.attention_mode)
  File "/projects/nmt/nmt-keras-master/src/keras/keras/layers/recurrent.py", line 91, in compute_attention
    alphas = K.softmax(K.reshape(e, [K.shape(e)[0], K.shape(e)[1]]))
  File "/projects/nmt/nmt-keras-master/src/keras/keras/backend/tensorflow_backend.py", line 3469, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample_ensemble.py", line 61, in <module>
    sample_ensemble(args, params)
  File "/projects/nmt/nmt-keras-master/nmt_keras/apply_model.py", line 39, in sample_ensemble
    models = [loadModel(m, -1, full_path=True) for m in args.models]
  File "/projects/nmt/nmt-keras-master/nmt_keras/apply_model.py", line 39, in <listcomp>
    models = [loadModel(m, -1, full_path=True) for m in args.models]
  File "/projects/nmt/nmt-keras-master/src/keras-wrapper/keras_wrapper/cnn_model.py", line 170, in loadModel
    model = model_from_json(open(model_name + '_structure.json').read(), custom_objects=custom_objects)
FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/CustomChat_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_50_structure.json'

------------------------------------------------------------------------

Regarding Bleu score
On epoch 17 I had
[16/10/2018 04:22:34] Bleu_1: 2.7894680872900676e-25
[16/10/2018 04:22:34] Bleu_2: 8.821072620600536e-21
[16/10/2018 04:22:34] Bleu_3: 2.789468089149716e-19
[16/10/2018 04:22:34] Bleu_4: 1.5686331819593597e-18

And suddenly on epoch 18 I had
[16/10/2018 04:22:52] Bleu_1: 0.0
[16/10/2018 04:22:52] Bleu_2: 0.0
[16/10/2018 04:22:52] Bleu_3: 0.0
[16/10/2018 04:22:52] Bleu_4: 0.0
```

**Comment by lvapeab** [comment]
I think you are using two different `tensorflow` versions (in your server and in your local machine).  And the local version is not compatible with the latest releases of `Keras`. Please, try to upgrade.

**Comment by jksignity** [comment]
Thanks, I'll try to update my local and see if it works.

Can you please help with the Bleu score part.

**Comment by lvapeab** [comment]
150 training samples represent very scarce resources. I'd try to acquire more data.
