### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by YZ576023775** [lvapeab/nmt-keras#88]
[10/11/2018 09:42:48] <<< Predicting outputs of val set >>>
Sampling 9829/9829  -  ETA: 0s
 Total cost of the translations: 786305.500000   Average cost of the translations: 79.998528
The sampling took: 2894.420971 secs (Speed: 0.294478 sec/sample)

[10/11/2018 10:31:02] Prediction output 0: target_text (text)
[10/11/2018 10:31:02] Decoding beam search prediction ...
[10/11/2018 10:31:02] Using heuristic 0
[10/11/2018 10:31:03] Evaluating on metric coco
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    train_model(parameters, args.dataset)
  File "/home/yz/others/nmt-keras/nmt_keras/training.py", line 159, in train_model
    nmt_model.trainNet(dataset, training_params)
  File "/home/yz/others/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 915, in trainNet
    self.__train(ds, params)
  File "/home/yz/others/nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 1140, in __train
    initial_epoch=params['epoch_offset'])
  File "/home/yz/others/nmt-keras/src/keras/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yz/others/nmt-keras/src/keras/keras/engine/training.py", line 1481, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yz/others/nmt-keras/src/keras/keras/engine/training_generator.py", line 223, in fit_generator
    callbacks.on_batch_end(batch_index, batch_logs)
  File "/home/yz/others/nmt-keras/src/keras/keras/callbacks.py", line 114, in on_batch_end
    callback.on_batch_end(batch, logs)
  File "/home/yz/others/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 292, in on_batch_end
    self.evaluate(self.cum_update, counter_name='iteration', logs=logs)
  File "/home/yz/others/nmt-keras/src/keras-wrapper/keras_wrapper/extra/callbacks.py", line 518, in evaluate
    split=s)
  File "/home/yz/others/nmt-keras/src/keras-wrapper/keras_wrapper/extra/evaluation.py", line 61, in get_coco_score
    score, _ = scorer.compute_score(refs, hypo)
  File "/home/yz/others/nmt-keras/src/coco-caption/pycocoevalcap/bleu/bleu.py", line 22, in compute_score
    assert (list(gts) == list(res))
AssertionError
Exception ignored in: <bound method Ter.__del__ of <pycocoevalcap.ter.ter.Ter object at 0x7f87f4327f60>>
Traceback (most recent call last):
  File "/home/yz/others/nmt-keras/src/coco-caption/pycocoevalcap/ter/ter.py", line 70, in __del__
    self.ter_p.kill()
AttributeError: 'Ter' object has no attribute 'ter_p'

help me to solve this.

**Comment by YZ576023775** [comment]
i use config_rnn.py.

**Comment by YZ576023775** [comment]
> Hi,
> 
> do you have `java` installed? This is required for evaluating the system.

yes . i have installed java, and i find list(res) length = 0.

**Comment by YZ576023775** [comment]
and how to train quick with 2 million dataset. how to set EVAL_EPOCH and   SAMPLE_EACH_UPDATES. i set EVAL_EPOCH = 3750 and SAMPLE_EACH_UPDATES = 30000. but i feel train slowly.

**Comment by lvapeab** [comment]
What is the average time per step?
Do you have `Tensorflow` or `Theano` properly installed and configured?
The use of `CuDNN` improves the speed with the `Tensorflow` backend.
