### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by jksignity** [lvapeab/nmt-keras#90]
Hi

I've trained a model on larger dataset but its showing the following error while testing

```
[03/12/2018 07:28:55] Reading parameters from config.py
[03/12/2018 07:28:55] <<< Cupy not available. Using numpy. >>>
Using TensorFlow backend.
[03/12/2018 07:28:56] <<< Cupy not available. Using numpy. >>>
[03/12/2018 07:28:56] Using an ensemble of 1 models
[03/12/2018 07:28:56] <<< Loading model from trained_models/JobKeyword_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_2_Model_Wrapper.pkl ... >>>
[03/12/2018 07:28:56] <<< Loading model from trained_models/JobKeyword_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_2.h5 ... >>>
2018-12-03 07:29:02.316719: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-03 07:29:02.317195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-12-03 07:29:02.317237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-12-03 07:29:02.721478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-03 07:29:02.721597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-12-03 07:29:02.721628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-12-03 07:29:02.721902: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2018-12-03 07:29:02.721984: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
[03/12/2018 07:29:03] <<< Loading optimized model... >>>
[03/12/2018 07:29:07] <<< Optimized model loaded. >>>
[03/12/2018 07:29:07] <<< Model loaded in 10.371 seconds. >>>
[03/12/2018 07:29:07] <<< Loading Dataset instance from datasets/Dataset_JobKeyword_esen.pkl ... >>>
[03/12/2018 07:29:09] <<< Dataset instance loaded >>>
Traceback (most recent call last):
  File "sample_ensemble.py", line 61, in <module>
    sample_ensemble(args, params)
  File "/content/text-classification/nmt_keras/apply_model.py", line 41, in sample_ensemble
    dataset = update_dataset_from_file(dataset, args.text, params, splits=args.splits, remove_outputs=True)
  File "/content/text-classification/data_engine/prepare_data.py", line 40, in update_dataset_from_file
    id=params['OUTPUTS_IDS_DATASET'][0])
  File "/content/text-classification/src/keras-wrapper/keras_wrapper/dataset.py", line 1306, in removeOutput
    del self.types_outputs[set_name][ind_remove]
TypeError: list indices must be integers or slices, not str
```
Can you please help with this.

Thanks

**Comment by lvapeab** [comment]
Hi, 

I'm unable to reproduce your error. Can you please check whether you have the repositories up to date?
`cd` into the `nmt-keras` folder and execute `git pull`. Next, `cd` to `src/keras-wrapper` and execute it again.

Thanks

**Comment by lvapeab** [comment]
What is the command you used to test?

**Comment by jksignity** [comment]
It started working now. I switched to a previous commit of keras_wrapper. But I use this command

```
!python sample_ensemble.py --models trained_models/text-classification/trained_models/JobKeyword_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_1 --dataset dataset/text-classification/datasets/Dataset_JobKeyword_esen.pkl --text examples/JobKeyword/test.es
```

Thanks
