### ISSUE TITLE
Error while Training

### ISSUE THREAD

**Issue by KushalDave** [lvapeab/nmt-keras#94]
Hi, I am trying to run your code with the default settings (I do not change anything) and run it on the data given on github with all default settings. I get the following error:

[17/01/2019 15:57:49] $HOME=C:\Users\dkay
[17/01/2019 15:57:49] CONFIGDIR=C:\Users\dkay\.matplotlib
[17/01/2019 15:57:49] matplotlib data path: C:\Program Files\Python35\lib\site-packages\matplotlib\mpl-data
[17/01/2019 15:57:49] loaded rc file C:\Program Files\Python35\lib\site-packages\matplotlib\mpl-data\matplotlibrc
[17/01/2019 15:57:49] matplotlib version 3.0.2
[17/01/2019 15:57:49] interactive is False
[17/01/2019 15:57:49] platform is win32
[17/01/2019 15:57:49] loaded modules: ['__mp_main__', '_bisect', 'unittest.suite', '_weakref', 'numpy.polynomial.legendre', 'tables.group', 'importlib.machinery
encoder', 'encodings.aliases', '_ctypes', 'pyparsing', 'numpy.lib.nanfunctions', 'email.feedparser', 'numpy.lib._iotools', 'numpy.fft.fftpack_lite', 'pkg_resour
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:\dkay\EEM\Code\nmt-keras\nmt-keras\nmt-keras\main.py", line 11, in <module>
    from nmt_keras.training import train_model
  File "D:\dkay\EEM\Code\nmt-keras\nmt-keras\nmt-keras\nmt_keras\training.py", line 10, in <module>
    from keras_wrapper.cnn_model import updateModel
  File "d:\dkay\python\python3.5.4\src\keras-wrapper\keras_wrapper\cnn_model.py", line 15, in <module>
    import keras
  File "d:\dkay\python\python3.5.4\src\keras\keras\__init__.py", line 3, in <module>
    from . import utils
  File "d:\dkay\python\python3.5.4\src\keras\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "d:\dkay\python\python3.5.4\src\keras\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "d:\dkay\python\python3.5.4\src\keras\keras\backend\__init__.py", line 92, in <module>
    from .tensorflow_backend import *
  File "d:\dkay\python\python3.5.4\src\keras\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\activations.py", line 24, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\utils\__init__.py", line 32, in <module>
    from tensorflow.python.keras.utils.io_utils import HDF5Matrix
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\keras\utils\io_utils.py", line 29, in <module>
    import h5py
  File "C:\Program Files\Python35\lib\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\h5r.pyx", line 145, in init h5py.h5r
AttributeError: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'
Press any key to continue . . .

I did install cython using pip, but I still get the same error. Do you know what could go wrong?

**Comment by lvapeab** [comment]
Hi,

this seems a problem when using the `h5py` bundled with Anaconda or Tensorflow for Windows (https://github.com/h5py/h5py/issues/1151). I have no access to a Windows machine, so I cannot reproduce the issue. Try downgrading the `h5py`  package.

**Comment by KushalDave** [comment]
I tried a lot of things did not work and left it to that. I instead just leverage the TranslationModel class from model_zoo.py in my script. Thanks.
